# /_config.yml
title: "Saudi Matjar"
description: "متجر منتجات"
url: "https://sherow1982.github.io"          # نطاق المستخدم/المؤسسة [ثابت]
baseurl: "/saudi-matjar.arabsad.com"         # اسم الريبو الفرعي

collections:
  products:
    output: true
    permalink: /product/:title/

defaults:
  - scope:
      type: products
    values:
      layout: product

markdown: kramdown
