# /_config.yml
title: "Saudi Matjar"
description: "متجر منتجات"

url: "https://sherow1982.github.io"
baseurl: "/saudi-matjar.arabsad.com"

remote_theme: sherow1982/fur-jekyll-theme-RTL

collections:
  products:
    output: true
    permalink: /product/:title/

defaults:
  - scope:
      type: products
    values:
      layout: product

markdown: kramdown
