name: Update Products Feed

on:
  schedule:
    - cron: '0 0 * * *'   # يوميًا عند منتصف الليل UTC
  workflow_dispatch:

permissions:
  contents: write          # الحد الأدنى المطلوب للدفع [web:195]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # قيّد التشغيل على main لتفادي دفع من فروع أخرى [web:49]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false     # أمنياً أفضل، سنمرر التوكن صراحة عند push [web:167]

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'         # تثبيت نسخة محددة لثبات البيئة [web:49]

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests bs4 lxml
        # يمكن إضافة hash pinning/constraints لاحقًا حسب الحاجة [web:49]

      - name: Run feed generator
        env:
          FEED_URL: ${{ secrets.FEED_URL }}  # اختياري
        run: |
          set -e
          python generate_feed.py
          # تحقّق من وجود الملف الناتج
          test -s products-feed.xml || (echo "products-feed.xml not found or empty" && exit 1)
        # set -e لوقف الخطوة عند أول فشل [web:49]

      - name: Commit and push updated feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          # إعداد هوية git محلياً فقط
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          # إضافة الملف الناتج
          git add products-feed.xml

          # إنشاء الالتزام فقط عند وجود تغييرات
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "[skip ci] Auto-update feed"

          # دفع آمن باستخدام GITHUB_TOKEN إلى نفس الفرع
          # مع 3 محاولات لتجاوز أعطال الشبكة المؤقتة
          for i in 1 2 3; do
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}" "HEAD:${{ github.ref_name }}" && break || \
            (echo "Push failed (attempt $i). Retrying in 5s..." && sleep 5)
          done
