from bs4 import BeautifulSoup

def text_or_none(tag):
    return tag.get_text(strip=True) if tag else None

def first_text(*vals):
    for v in vals:
        if v:
            return v
    return None

def generate_google_feed(root_xml: str):
    soup = BeautifulSoup(root_xml, 'xml')  # مهم مع g: namespace [web:6]
    items = soup.find_all('item') or soup.find_all('entry')

    records = []
    skipped = []

    for idx, item in enumerate(items, 1):
        gid = text_or_none(item.find('g:id'))
        plain_id = text_or_none(item.find('id'))
        title = text_or_none(item.find('g:title') or item.find('title'))
        link = text_or_none(item.find('g:link') or item.find('link'))
        price = text_or_none(item.find('g:price') or item.find('price'))
        availability = text_or_none(item.find('g:availability') or item.find('availability'))
        image_link = text_or_none(item.find('g:image_link') or item.find('image_link') or item.find('image'))
        desc = text_or_none(item.find('g:description') or item.find('description') or item.find('summary'))
        brand = text_or_none(item.find('g:brand') or item.find('brand'))
        condition = text_or_none(item.find('g:condition') or item.find('condition'))

        product_id = first_text(gid, plain_id, title, link)
        required_missing = [k for k, v in {
            "title": title, "link": link, "image_link": image_link,
            "price": price, "availability": availability
        }.items() if not v]

        if not product_id or required_missing:
            skipped.append(f"Entry #{idx} skipped: missing id or {required_missing}")
            continue

        records.append({
            "id": product_id, "title": title, "link": link, "price": price,
            "availability": availability, "image_link": image_link,
            "description": desc or title, "brand": brand, "condition": condition or "new",
        })

    print(f"✅ processed={len(records)} ⚠️ skipped={len(skipped)}")
    for m in skipped[:20]:
        print(" -", m)

    # ... أكمل كتابة products-feed.xml كما سبق دون افتراض وجود .text على عناصر مفقودة
