name: Sync EasyOrder Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # Every day at 03:00 UTC
  push:
    paths:
      - scripts/**.mjs
      - urls.json
      - package.json
      - package-lock.json
      - index.html

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Fetch legal pages
        run: npm run fetch:pages

      - name: Verify outputs
        run: |
          set -e
          test -s index.html || (echo "index.html not found or empty" && exit 1)
          test -d pages || (echo "pages/ directory not found" && exit 1)

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            ./index.html
            ./pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
